version: "3.7"
services:
    # bigger-db:
    #     build:
    #         context: ./dumps
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: backpack
    #         MYSQL_USER: docker
    #         MYSQL_PASSWORD: docker
    #     container_name: backpack_db
    #     ports:
    #         - "3308:3306"
    #     expose:
    #         - 3306
    #     tty: true
    bigger-backpack:
        container_name: bigger-backpack
        build: ./
        ports:
            - "127.0.0.1:5000:5000"
        # depends_on:
        #     - bigger-db
        volumes:
            - ./:/app
#https://askubuntu.com/questions/773446/unable-to-connect-via-mysql-workbench-to-localhost-in-ubuntu-16-04-passwordless
